### ISSUE TITLE
AttributeError: 'BoolOp' object has no attribute 'targets'

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#109]
Steps:
 1. Download the code from https://github.com/OCA/l10n-spain/pull/434
 2. Run the pylint checks

Saw:
https://travis-ci.org/OCA/l10n-spain/jobs/196441078#L569

```bash
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 201, in <module>
    ] + modules_changed_cmd + extra_params_cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 105, in main
    extra_params=extra_params)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 75, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/lint.py", line 1310, in __init__
    linter.check(args)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/lint.py", line 732, in check
    self._do_check(files_or_modules)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/lint.py", line 863, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/lint.py", line 944, in check_astroid_module
    walker.walk(ast_node)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 944, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint/utils.py", line 941, in walk
    cb(astroid)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint_odoo/checkers/no_modules.py", line 384, in visit_call
    field_name = (argument.parent.parent.targets[0].name
AttributeError: 'BoolOp' object has no attribute 'targets'
```

Thanks @pedrobaeza for reporting

**Comment by moylop260** [comment]
@JesusZapata 
Could you help us to fix it?
