### ISSUE TITLE
[TEST] Pylint error 

### ISSUE THREAD

**Issue by eilst** [OCA/pylint-odoo#262]
**Describe the bug**
[Travis red](https://travis-ci.com/eilst/server-auth/jobs/229060322
) 
Error when testing auth_saml:

************* Module auth_keycloak.examples.cli
```
auth_keycloak/examples/cli.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 59, in <module>
    result = run_pylint.pylint_run(is_pull_request, version, git_work_dir)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 169, in pylint_run
    real_errors = main(cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 318, in main
    extra_params=extra_params)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 286, in run_pylint
    pylint_res = pylint.lint.Run(cmd, do_exit=False)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint_odoo/misc.py", line 197, in visit_module
    self.wrapper_visit_module(node)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint_odoo/misc.py", line 183, in wrapper_visit_module
    if not check_method():
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pylint_odoo/checkers/modules_odoo.py", line 434, in _check_rst_syntax_error
    "%s:%d" % (rst_file, error.line),
TypeError: %d format: a number is required, not NoneType
```

**Comment by moylop260** [comment]
fix https://github.com/OCA/pylint-odoo/pull/261
