### ISSUE TITLE
AttributeError: module 'isort' has no attribute 'SortImports'

### ISSUE THREAD

**Issue by Yajo** [OCA/pylint-odoo#296]
I'm seeing this error:

```
pylint with mandatory checks.............................................Failed
- hook id: pylint
- exit code: 1

Traceback (most recent call last):
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint_odoo/checkers/modules_odoo.py", line 448, in visit_import
    self._check_imported_packages(node, name)
  File "/var/home/yajo/.cache/pre-commit/repoxf829pri/py_env-python3/lib/python3.8/site-packages/pylint_odoo/checkers/modules_odoo.py", line 406, in _check_imported_packages
    isort_obj = isort.SortImports(file_contents='')
AttributeError: module 'isort' has no attribute 'SortImports'
```

My pre-commit configuration is:

```yaml
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        name: pylint with optional checks
        args:
          - --valid_odoo_versions=12.0
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
        additional_dependencies: ["pylint-odoo==3.5.0"]
      - id: pylint
        name: pylint with mandatory checks
        args:
          - --valid_odoo_versions=12.0
          - --rcfile=.pylintrc-mandatory
        additional_dependencies: ["pylint-odoo==3.5.0"]
```

Possibly the isort dependency is not correctly pinned in this project's dependencies?

**Comment by Yajo** [comment]
Possibly related to https://github.com/PyCQA/isort/commit/c7378c3b77a115801200e7a20201075858997a28

**Comment by moylop260** [comment]
The following change:
 - https://github.com/PyCQA/isort/commit/c7378c3b77a115801200e7a20201075858997a28

Looks like a new change after isort >= 5.5.3

However, pylint-odoo requirements is using another old version:
 - https://github.com/OCA/pylint-odoo/blob/525cbf2679501ad112165e02ecad9ab39ec0d6df/requirements.txt#L2

I'm not sure how we could fix from this project.

**Comment by Yajo** [comment]
It seems that when you install `pylint` 2.6.0, [it pulls a newer isort than the one supported by pylint-odoo](https://github.com/PyCQA/pylint/blob/8197144d82469ed39d1f4f3c345efee198ec9212/pylint/__pkginfo__.py#L44).

The fix here should be to upgrade all dependencies, fix incompatibilities (such as the one in this issue) and release.

Downstream, one can [add this diff to `.pre-commit-config.yaml`](https://github.com/Tecnativa/doodba-copier-template/pull/111/files#diff-731e982b491cbb6b5c2d8eb2046a573b) to workaround the problem:

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 7960672..8090edc 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -87,13 +87,17 @@ repos:
           - --rcfile=.pylintrc
           - --exit-zero
         verbose: true
-        additional_dependencies: ["pylint-odoo==3.5.0"]
+        additional_dependencies:
+          - isort==4.3.21
+          - pylint-odoo==3.5.0
       - id: pylint
         name: pylint with mandatory checks
         args:
           - --valid_odoo_versions={{ "%.1f"|format(odoo_version) }}
           - --rcfile=.pylintrc-mandatory
-        additional_dependencies: ["pylint-odoo==3.5.0"]
+        additional_dependencies:
+          - isort==4.3.21
+          - pylint-odoo==3.5.0
   - repo: https://github.com/pre-commit/mirrors-eslint
     rev: v7.8.1
     hooks:
```

**Comment by moylop260** [comment]
@Yajo 

Currently, pylint-odoo latest version is compatible with `pylint==2.5.3` for py3:
 - https://github.com/OCA/pylint-odoo/blob/525cbf2679501ad112165e02ecad9ab39ec0d6df/requirements.txt#L9

Your pre-commit-config.yaml file is using `rev: pylint-2.6.0`
Please, Could you use `rev: pylint-2.5.3` instead?

**Comment by Yajo** [comment]
OK, I've done that in https://github.com/OCA/oca-addons-repo-template/pull/8, thanks.
