### ISSUE TITLE
Pylint crashes when object is str

### ISSUE THREAD

**Issue by Yenthe666** [OCA/pylint-odoo#331]
Steps to reproduce:
1. Clone `git clone https://github.com/OCA/rma`
2. Checkout `10.0`
3. Run Pylint from the terminal on the module `crm_claim_ext`:
```
pylint --load-plugins=pylint_odoo --disable=C -f json crm_claim_ext
```

Result:
```
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/misc.py", line 217, in visit_module
    self.wrapper_visit_module(node)
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/misc.py", line 203, in wrapper_visit_module
    if not check_method():
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 871, in _check_file_not_used
    set(self._get_xml_referenced_files())
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 843, in _get_xml_referenced_files
    self._get_xml_referenced_files_report(fname, data_type)
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 853, in _get_xml_referenced_files_report
    for attribute in ['xml', 'xsl']
  File "/usr/local/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 855, in <dictcomp>
    os.path.join(self.module_path, fname)
AttributeError: 'str' object has no attribute 'xpath'
```

I wasn't really able to figure out the why though so couldn't come up with a fix 🤔 @lmignon @moylop260 any chance one of you could give me a pointer here?

**Comment by moylop260** [comment]
Hi @Yenthe666 

I just realized that pylint-odoo is not supporting xml with syntax errors well

The following line:
 - `self.parse_xml(os.path.join(self.module_path, fname))`

Returned a string with the following content instead of a xml object:
 - `Opening and ending tag mismatch: page line 30 and field, line 33, column 21 (crm_claim_ext_view.xml, line 33)`

It is the following file: `rma/crm_claim_ext/crm_claim_ext_view.xml`
 - https://github.com/OCA/rma/blob/d8d1bdbd9c09c74f9cd1ad12e13db884712cc9f3/crm_claim_ext/crm_claim_ext_view.xml#L30-L33

Even with this issue in pylint the source could be fixed using the following change:

```diff
       <record model="ir.ui.view" id="crm_claim_rma_form_view">
            <field name="name">CRM - Claim product return Form</field>
            <field name="model">crm.claim</field>
            <field name="inherit_id" ref="crm_claim.crm_case_claims_form_view"/>
            <field name="arch" type="xml">
            <page string="Communication &amp; History" position="after">
-                <page string="Product return">
+                <page string="Product return"/>
                </page>
            </field>
        </record>
```

**Comment by Yenthe666** [comment]
Aha, interesting! I think that Odoo might actually accept both cases 🤔 Shall I make a PR against 10.0 to get this sorted?
From the other side: how can we secure this when it happens for any other apps with `pylint`?

**Comment by moylop260** [comment]
@Yenthe666 

That module is not installed in the CI because is not active/installable:
 - https://github.com/OCA/rma/blob/c8e343d7d274c7580564edc953f8dae0d593f630/crm_claim_ext/__manifest__.py#L54-L55

Odoo doesn't support to load a xml with syntax error

I just made the following PR in order to avoid crasing pylint when a xml has syntax error:
 - https://github.com/OCA/pylint-odoo/pull/343

**Comment by Yenthe666** [comment]
Thanks ❤️
